name: Percy Visual Test CI
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
      
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Install Percy CLI
      run: npm install -g @percy/cli
    
    - name: Set Percy token as secret variable
      run: echo "PERCY_TOKEN=${{ secrets.PERCY_TOKEN }}" >> $GITHUB_ENV
      
    - name: Set Percy variables
      run: |
        echo "PERCY_COMMIT=${{ github.sha }}" >> $GITHUB_ENV
        # Use special branch naming for PRs to enable proper comparisons
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          echo "PERCY_BRANCH=pull/${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "PERCY_TARGET_BRANCH=${{ github.base_ref }}" >> $GITHUB_ENV
        else
          # For direct pushes, use the branch name
          echo "PERCY_BRANCH=${{ github.ref_name }}" >> $GITHUB_ENV
          
          # If not on main/master, compare against main
          if [[ "${{ github.ref_name }}" != "main" && "${{ github.ref_name }}" != "master" ]]; then
            echo "PERCY_TARGET_BRANCH=main" >> $GITHUB_ENV
          fi
        fi
    
    - name: Build with Maven
      run: mvn clean install -DskipTests
    
    - name: Run Tests with Percy
      run: npx percy exec -- mvn test -Dtest=BajajDemoTest
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/surefire-reports/